name: Kenny on IT
description: A small talks for IT
meta_description: "Kenny Github Blog. IT stuffs"

markdown: kramdown
highlighter: rouge
logo: false
exclude:
  - LICENSE.txt
  - README.md

baseurl: ""

domain_name: "https://kenny.yeoyou.net"
google_analytics: "UA-XXXXXXXX-X"

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate

# paginate
paginate: 10

# Details for the RSS feed generator
url: ""
author: "Kenny Yeo"

# Disqus config
disqus-shortname: "kennyyeoyounet"

# jekyll-multiple-languages-plugin
languages: ["en", "ko", "ja"]

exclude_from_localizations:
  - assets
  - index.html

# Moving above is not happening on Github Action so disable this
# default_locale_in_subfolder: true
